version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3

jobs:
  build:
    docker:
      - image: cimg/node:18.11.0@sha256:41530b8efde8b71bb5439ac33f02dbcc9b92d65dd3e7e47430cac6513e5a1edf

    steps:
      - checkout

      - run:
          name: installing modules
          # with nodejs 18 the resolution for peer dependencies changed
          # right now we need to force legacy peer dependency resolution
          command: npm ci --legacy-peer-deps

      - run:
          name: testing
          command: npm run test

      - run:
          name: building
          command: npm run build

      - persist_to_workspace:
          root: ./build
          paths:
            - '*'

  deploy:
    executor: aws-cli/default

    steps:
      - aws-cli/setup
      - attach_workspace:
          at: ./build
      - run:
          command: |
            aws s3 sync --delete ./build s3://$S3_TARGET/ --exclude "index.html"
            aws s3 sync --delete ./build s3://$S3_TARGET/ --cache-control "max-age=0" --include "index.html"


workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main